name: Trigger auto deployment for open-liberity

# When this action will be executed
on:
  # Automatically trigger it when detected changes in this repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/open-liberity-AutoDeployTrigger-fe296892-b8ea-4ff0-9732-87b7c18216da.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.OPENLIBERITY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OPENLIBERITY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OPENLIBERITY_AZURE_SUBSCRIPTION_ID }}

      - name: Azure Container Apps Build and Deploy for Java            
        uses: showpune/container-apps-deploy-action@v0.0.7
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.OPENLIBERITY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OPENLIBERITY_REGISTRY_PASSWORD }}
          containerAppName: open-liberity
          resourceGroup: zhiyongli-tanzu
          imageToBuild: showpune/open-liberity:${{ github.sha }}
          volumeMount:  ' --volume ${{ github.workspace }}/config:/bindings:ro '


